version: '3.8'
services:
  devDb:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=altschool
    networks:
      - altschool
networks:
  altschool:
